### ISSUE TITLE
Ramadan to-do list

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend#312]
- [ ] Integrate new https://github.com/thgreasi/babel-plugin-system-import-transformer/issues/5#issuecomment-223132892
- [ ] Add gapless options for reciters
- [ ] Improve search results speed
- [ ] Deployment -> Kubernetes?
- [ ] Production log, see: https://github.com/quran/quran.com-api/issues/53
- [ ] gzip fonts
- [ ] Add banner for mobile apps
- [x] word by word audio improvements #333
- [x] Facebook/Twiter share
- [x] Change support for web widget https://developer.zendesk.com/embeddables/docs/widget/api
- [x] Allow for transliteration in the tooltips #376
- [x] Zero padding for urls `/07`
- [x] Audioplayer bugs, https://github.com/quran/quran.com-frontend/issues/276
- [x] Fix SEO searchaction snippet
- [x] Make surah info description available for SEO
- [x] userAgent reduce size
- [x] Increase site speed -> Currently, API responding at 1.5s. Need to reduce it to under 1s. Potentially either improving the first query or warming up the cache on deployments, see https://github.com/quran/quran.com-api/pull/58
- [x] Load images from CDN, #326

**Comment by AhmedShab** [comment]
Hi @mmahalwy, what do you mean by audioplayer bugs? Is that the issue #276 ?

**Comment by mmahalwy** [comment]
@AhmedShab yes. Updated ^^

**Comment by AhmedShab** [comment]
@mmahalwy I think I have to spend sometime to learn Reactjs, Redux and Webpack since I'm not familiar with those technologies. 

I tried to look into the code and see if I can understand how to increase the respond time (since @azizur  is looking into the Audioplayer bugs) but not sure where to start.

It might take me longer but I'm gonna help with what I can :)

**Comment by azizur** [comment]
@AhmedShab you can still help with it. I just started to work on it, if you like we can both work together on it.

**Comment by AhmedShab** [comment]
cool @azizur, will have to go over Reactjs first like I said then will get into it

**Comment by mmahalwy** [comment]
@AhmedShab I am pushing a PR inshallah tonight to help with response time.

**Comment by sabeurthabti** [comment]
Can we add `https` support to this list? Who is the CDN?

**Comment by mmahalwy** [comment]
re @sabeurthabti's comment: @ahmedre ^^

**Comment by ahmedre** [comment]
yep, it's on my todo list insha'Allah.
our cdn supports it, we just need to get the certs and set up our servers to support it.

**Comment by mmahalwy** [comment]
@ahmedre Rapidssl?
